### ISSUE TITLE
undefined reference to `Fl

### ISSUE THREAD

**Issue by KC7NOA** [ve7fet/linuxax25#2] opened 2016-10-13 03:54 UTC
make[2]: Entering directory `/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl'
g++ -std=gnu++11  -g -O2  -lX11 -lfltk -lGL  -lSM -lICE -lXi -lXext -lX11  ../hdrvcomm.o  -o xfsmmixer xfsmmixer.o xfsmmixer_main.o  
xfsmmixer_main.o: In function`main':
/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:321: undefined reference to `Fl::arg(int, char**, int&)'
/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:416: undefined reference to`Fl_Slider::bounds(double, double)'

lots of them ... looks like
ax25tools/hdlcutil/fl/xfsmmixer is the root ...

Im on Odroid-X2 Ubuntu 14.04 Linux odroid 3.8.13.303 #1 SMP PREEMPT Mon May 9 12:02:41 PDT 2016 armv7l armv7l armv7l GNU/Linux

looks like it compiled fine on my Intel based system, but not my arm ....

Im kinda stuck with that version of kernel, Odroid has not updated it in over 2 years ...

**Comment by f6bvp** [comment] 2016-10-14 10:15
Hi,

I never experienced such issue, for standard install never compiled this 
option.

How did you manage to built "fl" sub functions ?

Some options in configure ?

According to listing of |xfsmmixer_main.cxx|

this is the source of soundmodem soundcard radio modem driver from 
Thomas Sailer.

Are you sure you need it ?

Initial comments of source file says :

|upgraded to fltk 1.0.3|

||It is possible that the driver needs some fltk libraries ?


      FLTK <http://www.fltk.org/>

www.*fltk*.org/
Traduire cette page 
<https://translate.google.fr/translate?hl=fr&sl=en&u=http://www.fltk.org/&prev=search>
The Fast Light Toolkit is a cross-platform Graphical User Interface 
library written in C++. Site includes downloads, documentation, 
screenshots of widgets, ...

73 de Bernard, f6bvp

**Comment by KC7NOA** [comment] 2016-10-14 22:17
ok .. i didn't do much but run the install script updAX25.sh ... i didn't change anything

**Comment by KC7NOA** [comment] 2016-10-15 00:02
Line 41 says its detected

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gawk... (cached) gawk
checking for a sed that does not truncate output... /bin/sed
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... -std=gnu11
checking whether gcc -std=gnu11 understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc -std=gnu11... gcc3
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... -std=gnu++11
checking dependency style of g++ -std=gnu++11... gcc3
checking how to run the C preprocessor... gcc -std=gnu11 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking whether gcc -std=gnu11 needs -traditional... no
checking whether ln -s works... yes
checking for X... libraries , headers 
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking for zlibVersion in -lz... yes
checking for ax25_config_load_ports in -lax25... yes
checking for openpty in -lutil... yes
checking for main in -lGL... yes
checking for main in -lfltk... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for sys/time.h... yes
checking for vfork.h... no
checking for sys/select.h... yes
checking for sys/socket.h... yes
checking for utime.h... yes
checking for arpa/inet.h... yes
checking for fcntl.h... yes
checking for limits.h... yes
checking for netdb.h... yes
checking for netinet/in.h... yes
checking for paths.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for sys/file.h... yes
checking for sys/ioctl.h... yes
checking for sys/param.h... yes
checking for sys/socket.h... (cached) yes
checking for sys/time.h... (cached) yes
checking for syslog.h... yes
checking for termios.h... yes
checking for unistd.h... (cached) yes
checking for utime.h... (cached) yes
checking for utmp.h... yes
checking for zlib.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for an ANSI C-conforming const... yes
checking for uid_t in sys/types.h... yes
checking for pid_t... yes
checking for mode_t... yes
checking for size_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking for working chown... yes
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for GNU libc compatible malloc... yes
checking for working memcmp... yes
checking types of arguments for select... int,fd_set *,struct timeval *
checking return type of signal handlers... void
checking whether lstat correctly handles trailing slash... yes
checking whether stat accepts an empty string... no
checking for working strtod... yes
checking whether utime accepts a null argument... yes
checking for alarm... yes
checking for atexit... yes
checking for dup2... yes
checking for endgrent... yes
checking for endpwent... yes
checking for gethostbyname... (cached) yes
checking for gethostname... yes
checking for gettimeofday... yes
checking for inet_ntoa... yes
checking for memmove... yes
checking for memset... yes
checking for mkdir... yes
checking for select... yes
checking for socket... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strrchr... yes
checking for strspn... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
checking for uname... yes
checking for utime... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating netrom/Makefile
config.status: creating tcpip/Makefile
config.status: creating ax25/Makefile
config.status: creating ax25/axgetput/Makefile
config.status: creating Makefile
config.status: creating rose/Makefile
config.status: creating user_call/Makefile
config.status: creating kiss/Makefile
config.status: creating 6pack/Makefile
config.status: creating hdlcutil/Makefile
config.status: creating hdlcutil/fl/Makefile
config.status: creating yamdrv/Makefile
config.status: creating dmascc/Makefile
config.status: creating doc/Makefile
config.status: creating man/Makefile
config.status: creating etc/Makefile
config.status: creating ax25tools.spec
config.status: creating config.h
config.status: executing depfiles commands

**Comment by KC7NOA** [comment] 2016-10-19 03:15
it looks like an undefined reference in

make[2]: Leaving directory `/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil'
Making install in fl
make[2]: Entering directory `/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl'
g++ -std=gnu++11  -g -O2  -lX11 -lfltk -lGL  -lSM -lICE -lXi -lXext -lX11  ../hdrvcomm.o  -o xfsmmixer xfsmmixer.o xfsmmixer_main.o  
xfsmmixer_main.o: In function `main':
/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:321: undefined reference to `Fl::arg(int, char**, int&)'
/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:416: undefined reference to `Fl_Slider::bounds(double, double)'
/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:418: undefined reference to `Fl_Valuator::value(double)'
/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:420: undefined reference to `Fl_Slider::bounds(double, double)'
/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:422: undefined reference to `Fl_Valuator::value(double)'
/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:424: undefined reference to `Fl_Slider::bounds(double, double)'
/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:426: undefined reference to `Fl_Valuator::value(double)'
/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:428: undefined reference to `Fl_Slider::bounds(double, double)'
/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:430: undefined reference to `Fl_Valuator::value(double)'
/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:432: undefined reference to `Fl_Button::value(int)'
/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:433: undefined reference to `Fl_Button::value(int)'
/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:434: undefined reference to `Fl_Button::value(int)'
/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:435: undefined reference to `Fl_Button::value(int)'
/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:436: undefined reference to `Fl_Button::value(int)'
xfsmmixer_main.o:/usr/local/src/ax25/linuxax25-master/ax25tools/hdlcutil/fl/xfsmmixer_main.cxx:437: more undefined references to `Fl_Button::value(int)' follow

nothing to do with fltk

**Comment by KC7NOA** [comment] 2016-10-19 03:16
This did build on a RaspBerryPi-B recently ... perhaps i should D/L and try to install again ...

**Comment by dranch** [comment] 2019-02-09 04:00
Unless you *really* need the deprecated sm support which was later replaced with Tom Sailer's soundmodem program (also deprecated), just do a "./configure --without-x".  Btw, things DO compile here ok on Centos6 but I *do* recommend to skip these now obsolete accessory programs.

**Comment by ve7fet** [comment] 2019-02-10 03:36
Root cause of the issue was flags being passed to the compiler, instead of the linker. So all the necessary libraries weren't available to link.

The configure script has also been updated such that it will never attempt to build these utilities, unless you pass the --with-xutils option to ./configure. So, you must REALLY want to build them, can't do it by accident, if you happen to have all the dependencies installed.

Configure also does a better job of checking for the required X and FLTK header files, and will abort if it can't find the ones it needs.

This is now fixed in axtools 1.0.5 (still in development, not yet released, just clone the master).

**Closed by ve7fet** 2019-02-10 03:36 UTC
